version: "3"

services:
  web:
    image: node:19-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
    working_dir: /web
    entrypoint: npm
    command:
      - run
      - start
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: password1
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379

  mysql:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
